# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180617_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='image',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='image',
            name='vote_score',
        ),
    ]
